server:
  port: 8080
  context-path: /demo
#logging:
#  file: mylog.log
# path: E:\log
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    # reasonable 为false 超过页数返回空
    reasonable: false   
    supportMethodsArguments: true
    params: count=countSql
thymeleaf:
   prefix: classpath:/templates/
   suffix: .html
   cache: false
   content-type: text/html
   enabled: true
   encoding: UTF-8
   mode: HTML5
   #redis
redis:
   host: 127.0.0.1
   port: 6379
   timeout: 3
   password: 123456
   poolMaxTotal: 10
   poolMaxIdle: 10
   poolMaxWait: 3
   

#rabbitmq
rabbitmq:
   host: 127.0.0.1
   port: 5672
   username: guest
   password: guest
   virtual-host: /
   listener: 
       simple:
           concurrency: 10
           max-concurrency: 10
           prefetch: 1
           auto-startup: true
           default-requeue-rejected: true
   template:
       retry:
          enabled: true 
          initial-interval: 1000 
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0